//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboris.Cosan.UI.ViewWeb {
    
    
    public partial class AmbienteAspx {
        
        /// <summary>
        /// styleDinamicoBannerAmbiente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl styleDinamicoBannerAmbiente;
        
        /// <summary>
        /// AbasMenu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Laboris.Cosan.UI.ViewWeb.Controls.AbasMenu AbasMenu1;
        
        /// <summary>
        /// NossosParceiros1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Laboris.Cosan.UI.ViewWeb.Controls.NossosParceiros NossosParceiros1;
        
        /// <summary>
        /// lblAmbienteAtual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblAmbienteAtual;
        
        /// <summary>
        /// PrateleiraProdutos1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Laboris.Cosan.UI.ViewWeb.Controls.PrateleiraProdutos PrateleiraProdutos1;
        
        /// <summary>
        /// NaveguePorTemas1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Laboris.Cosan.UI.ViewWeb.Controls.NaveguePorTemas NaveguePorTemas1;
    }
}
